### PR TITLE
few examples of OpenMP matrix mux using schema type compiler and

### PR DESCRIPTION
**Pull request by shahzebsiddiqui**
module_iterator

### CODE REVIEW

**Comment by shahzebsiddiqui** [comment]
@vsoch let me know your thoughts. These are just some ideas i was thinking about. I can think of `module_iterator` be an extension of the `script` schema that can run script against multiple modules. Equivalent of running a single program permutation across several modules. My thought is most simple scripts like compilation with compilers can be tested with more than one version. There can be cases where a specific compiler version changes some flag names that are not compatible with older versions but goal is to increase user productivity where repetition can be made simple with power of YAML. I kinda like the way Travis allow matrix build https://docs.travis-ci.com/user/build-matrix/ for running scripts. I was trying to do something similar with the `run` key.

**Comment by shahzebsiddiqui** [comment]
I have not figured out how `type: compiler` will generate the script so thats why i have added ``test[1|2].sh`` to describe how these tests will work. 

The idea was to build one source code with multiple compilers without recreating a new sub-test.

**Comment by vsoch** [comment]
I think having a build matrix is out of scope for now too.

**Comment by shahzebsiddiqui** [comment]
> This needs to hold off until the type is designed and defined in the schemas repository. We should not add anything new here until that is done (and in fact we will likely need to remove / edit the tutorials that are now here that don't have a type). Before that happens, the support for these schemas needs to be added, period. Let's leave this open for now, and address when those criteria are met.

I agree, this was not meant to be merged now. I find it easier to write out the test configuration before writing the schema.

**Pull request closed without merging**
